### PR TITLE
Updated Simplified Chinese language file

### PR DESCRIPTION
**Pull request by shinyoyo**
Updated Simplified Chinese language file to match the lasted version of webman mod

### CODE REVIEW

**Comment by Matsumot0** [comment]
Can you just leave in XML file the names of icons?

**Comment by shinyoyo** [comment]
The Chinese xml is too old,all icon name change is match the lastest english webman.xml.If leave these old icon entry will make webman's menu error at chinese lanuage file.

**Comment by Matsumot0** [comment]
Nevermind, the latest webMAN.xml isn't updated at all.
I will edit after i've merge your changes.

**Comment by shinyoyo** [comment]
OK,currnet other old luange file may be has same menu icon display issues (insert disc,unload disc icon not shwn,some menu item miss),because the old xml file.

**Comment by Matsumot0** [comment]
Done.

**Pull request closed without merging**
